crystalcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls'))
]

main_app/urls.py
from django.urls import path
from . import views


urlpatterns = [
  path('', views.home, name='home'),
  path('about/', views.about, name='about'),
  path('crystals/', views.crystals_index, name='index'),
  path('crystals/<int:crystal_id>/', views.crystals_detail, name='detail'),
  path('crystals/create', views.CrystalCreate.as_view(), name='crystals_create'),
  path('crystals/<int:crystal_id>/add_reading/', views.add_reading, name='add_reading'),
  path('crystals/<int:crystal_id>/assoc_collection/<int:collection_id>/', views.assoc_collection, name='assoc_collection'),
  path('crystals/<int:crystal_id>/remove_assoc_collection/<int:collection_id>/', views.remove_assoc_collection, name='remove_assoc_collection'),
  path('crystals/<int:pk>/update/', views.CrystalUpdate.as_view(), name='crystals_update'),
  path('crystals/<int:pk>/delete/', views.CrystalDelete.as_view(), name='crystals_delete'),
  path('collections/', views.CollectionList.as_view(), name='collections_index'),
  path('collections/<int:pk>/', views.CollectionDetail.as_view(), name='collections_detail'),
  path('collections/create/', views.CollectionCreate.as_view(), name='collections_create'),
  path('collections/<int:pk>/update/', views.CollectionUpdate.as_view(), name='collections_update'),
  path('collections/<int:pk>/delete/', views.CollectionDelete.as_view(), name='collections_delete'),

]

main_app/models.py
from django.db import models
from django.urls import reverse
REASONS = (
    ('H', 'Health'),
    ('E', 'Emotional'),
    ('S', 'Spiritual'),
    ('C', 'Career'),
)
# Create your models here.
    
class Collection(models.Model):
     name = models.CharField(max_length=100)
     image = models.URLField()

     def __str__(self):
       return self.name

     def get_absolute_url(self):
       return reverse('collections_detail', kwargs={'pk': self.id})

class Crystal(models.Model):
    name = models.CharField(max_length=100)
    color = models.CharField(max_length=100)
    properties = models.TextField(max_length=250)
    image = models.URLField(blank=True)
    zodiac = models.CharField(max_length=100)
    collections = models.ManyToManyField(Collection)

    def __str__(self):
        return f'{self.name} ({self.id})'
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'crystal_id': self.id})
    
       
class Reading(models.Model):
    date = date = models.DateField('reading date')
    reason = models.CharField(
        max_length=50,
        choices = REASONS)
    crystal = models.ForeignKey(Crystal, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.get_reason_display()} on {self.date}"
    

   

main_app/forms.py
from django.forms import ModelForm
from .models import Reading

class ReadingForm(ModelForm):
  class Meta:
    model = Reading
    fields = ['date', 'reason']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Crystal, Collection
from .forms import ReadingForm



# Create your views here.
def home(request):
  return render(request, 'home.html')

def about(request):
  return render(request, 'about.html')

def crystals_index(request):
  crystals = Crystal.objects.all()
  return render(request, 'crystals/index.html',
                 {
                   'crystals': crystals
                   })
def crystals_detail(request, crystal_id):
  crystal = Crystal.objects.get(id=crystal_id)
  id_list = crystal.collections.all().values_list('id')
  not_in_collection = Collection.objects.exclude(id__in=id_list)
  reading_form = ReadingForm()
  return render(request, 'crystals/detail.html', 
                {
                'crystal': crystal, 
                'reading_form': reading_form,
                'collections': not_in_collection
                })
                
def assoc_collection(request, crystal_id, collection_id):
  Crystal.objects.get(id=crystal_id).collections.add(collection_id)
  return redirect('detail', crystal_id=crystal_id)

def remove_assoc_collection(request, crystal_id, collection_id):
  Crystal.objects.get(id=crystal_id).collections.remove(collection_id)
  return redirect('detail', crystal_id=crystal_id )

def add_reading(request, crystal_id):
    form = ReadingForm(request.POST)
    if form.is_valid():
     new_reading = form.save(commit=False)
     new_reading.crystal_id = crystal_id
     new_reading.save()
    return redirect('detail', crystal_id=crystal_id)
  
class CrystalCreate(CreateView):
  model = Crystal
  fields = ['name', 'color', 'properties', 'image', 'zodiac']

class CrystalUpdate(UpdateView):
  model = Crystal
  fields = ['color', 'properties', 'image', 'zodiac']

class CrystalDelete(DeleteView):
  model = Crystal
  success_url = '/crystals'

class CollectionList(ListView):
  model = Collection

class CollectionDetail(DetailView):
  model = Collection

class CollectionCreate(CreateView):
  model = Collection
  fields = '__all__'

class CollectionUpdate(UpdateView):
  model = Collection
  fields = ['name', 'image']

class CollectionDelete(DeleteView):
  model = Collection
  success_url = '/collections'
  

main_app/templates/about.html
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

{% extends 'base.html' %}

{% block content %}


<div class ="center">
  <h1>About the Crystal Collector</h1>
  <p>"In turbulent times, we can utilize grounding, tangible tangible tools to calm anxiety and soothe stress - like Crystals. </p>
  
</div>
</div>
  <hr />
    <h2 class="center">Crystal Healing</h2>
  <div class="carousel carousel-slider">
    <a class="carousel-item" style="color:black">Promote Good Energy<img src="https://totemsurftribe.files.wordpress.com/2024/04/4b1b0b68-0107-445e-8a26-8c3d41918297.jpeg?resize=438%2C438" class="sliding-img">
    <a class="carousel-item" style="color:black">Help Manifest<img src="https://totemsurftribe.files.wordpress.com/2024/04/554fff23-2b56-4a01-8971-fb5c9f09c742.jpeg?resize=438%2C438" class="sliding-img">
    <a class="carousel-item" style="color:black">Better Sleep<img src="https://totemsurftribe.files.wordpress.com/2024/04/1853847c-bfd5-4a19-b975-2f2bf76d1174.jpeg?resize=438%2C438" class="sliding-img">
    <a class="carousel-item" style="color:black">Physical and Emtional Benefits<img src="https://totemsurftribe.files.wordpress.com/2024/04/37c8dd27-4456-40a5-8629-919fbeb8cd2a.jpeg?resize=438%2C438" class="sliding-img">
  </div>
  <p>Inquire Now For A Free Initial Reading </p>
 <script>
  document.addEventListener('DOMContentLoaded', function() {
    carouselEl = document.querySelectorAll('.carousel');
    var instances = M.Carousel.init(carouselEl);
  });
 </script>
{% endblock %}

<footer>All Rights Reserved, &copy; 2024 Crystal Collector</footer>  
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="icon" type="image/x-icon" href="https://cdn-icons-png.flaticon.com/128/3426/3426146.png">
  <title>Crystal Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>

<body>
  <ul id="slide-out" class="sidenav">

    <ul class="center">
      <div>
        <a href="{% url 'home' %}"><img
            src="https://totemsurftribe.files.wordpress.com/2024/04/crystalcollectorlogo.png?resize=438%2C438"
            class="logo-img">
        </a>
      </div>
      <li><a href="{%  url 'about' %}">About</a></li>
      <li><a href="{%  url 'crystals_create' %}">Add A Crystal</a></li>
      <li><a href="{%  url 'index' %}">View All Crystals</a></li>
      <li><a href="{% url 'collections_create' %}">Create Unique Collection</a></li>
      <li><a href="{% url 'collections_index' %}">Browse All Collections</a></li>
    </ul>
  </ul>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">

        <nav> <!-- navbar content here  --> </nav>
        <ul id="slide-out" class="sidenav sidenav-fixed">

          <ul class="center">
            <div>
              <a href="{% url 'home' %}"><img
                  src="https://totemsurftribe.files.wordpress.com/2024/04/crystalcollectorlogo.png?resize=438%2C438"
                  class="logo-img">
              </a>
            </div>
            <li><a href="{%  url 'about' %}">About</a></li>
            <li><a href="{%  url 'crystals_create' %}">Add A Crystal</a></li>
            <li><a href="{%  url 'index' %}">View All Crystals</a></li>
            <li><a href="{% url 'collections_create' %}">Create Unique Collection</a></li>
            <li><a href="{% url 'collections_index' %}">Browse All Collections</a></li>
          </ul>
        </ul>

        <a href="#" data-target="slide-out" class="sidenav-trigger"><i class="material-icons">menu</i></a>
  </header>



  <main class="container">
    {% block content %}
    {% endblock %}

    <script>

      document.addEventListener('DOMContentLoaded', function () {
        const navEl = document.querySelector('.sidenav');
        var instances = M.Sidenav.init(navEl, {

        })

        var collapsibleElem = document.querySelector('.collapsible');
        var collapsibleInstance = M.Collapsible.init(collapsibleElem, options);

      });

    </script>
  </main>


  <footer class="page-footer">
    <div class="container">
      <div class="row">
        <div class="right">All Rights Reserved, &copy; 2024 Crystal Collector &nbsp;
        </div>
      </div>
    </div>
  </footer>
</body>

</html>

main_app/templates/crystals/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Crystal Details</h1>
<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ crystal.name }}</span>
        <p>Color: {{ crystal.color }}</p>
        <p>Properties: {{ crystal.properties }}</p>
        <p>Associated Signs: {{ crystal.zodiac }}</p>

        <img src=" {{crystal.image }} " class="detail-img">
      </div>
      <div class="card-action">
        <a href="{% url 'crystals_update' crystal.id %}"><i class="material-icons">edit</a>
        <a href="{% url 'crystals_delete' crystal.id %}"><i class="material-icons">delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
    <form method="POST" action="{%url 'add_reading' crystal.id%}">
      {%csrf_token%} {{reading_form.as_p}}
      <input type="submit" class="btn" value="Schedule Healing Session" />
    </form>
    <table class="striped, z-depth-1">
      <thead>
        <tr>
          <th>Date</th>
          <th>Reading</th>
        </tr>
      </thead>
      <tbody>
        {% for reading in crystal.reading_set.all %}
        <tr>
          <td>{{ reading.date }}</td>
          <td>{{ reading.get_reason_display }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<!-- New Markup Above -->

<hr>
<div class="row">
  <div class="col s6">
    <h5>{{ crystal.name }} is in</h5>
    {% if crystal.collections.count %}
    {% for collection in crystal.collections.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title">
          <span>{{ collection.name }}</span> <img src="{{ collection.image }}" class="collection-img">
        </span>
      </div>
      <div class="card-action">
        <form action="{% url 'remove_assoc_collection' crystal.id collection.id %}" method="POST">
          {% csrf_token %}
          <button type="submit" class="btn">Remove</button>

        </form>
      </div>
    </div>
    {% endfor %}
    {% else %}
    <h5>Not in any collections yet</h5>
    {% endif %}
  </div>


  <div class="col s6">
    <h4>Add to a Collection</h4>
    {% if collections.count %}
    {% for collection in collections.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title">
          <span>{{ collection.name }}</span> <img src="{{ collection.image }}" class="collection-img">
        </span>
      </div>
      <div class="card-action">
        <form action="{% url 'assoc_collection' crystal.id collection.id %}" method="POST">
          {% csrf_token %}
          <button type="submit" class="btn">Add</button>
        </form>
      </div>
    </div>
    {% endfor %}
    {% else %}
    <h5>{{crystal.name}} exists in all Collections</h5>
    {% endif %}



    <script>
      const dateEl = document.getElementById('id_date')
      M.Datepicker.init(dateEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true,
      })

      const selectEl = document.getElementById('id_reason')
      M.FormSelect.init(selectEl)
    </script>
    {% endblock %}

main_app/templates/crystals/index.html
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
{% extends 'base.html' %} {% block content %}

<h1>Crystals Collection</h1>

{% for crystal in crystals %}
<div class="row">
  <div class="col s12 m7">
    <div class="card">
      <div class="card-image">
        <img src=" {{crystal.image }} " />
        <span class="card-title" style="color: black">{{ crystal.name }}</span>
      </div>
      <div class="card-content">
        <p>Assicated Zodiac: {{crystal.zodiac}}</p>
      </div>
      <div class="card-action">
        <a href="{%  url 'detail' crystal.id %}"><i class="material-icons">list</i></a>

        <a href="#" class="favorite" data-crystal-id="{{ crystal.id }}">
          <i class="material-icons">favorite_border</i>
          <!-- <i class="material-icons" class="hidden">favorite</i> -->
          
        </a>
      </div>
    </div>
  </div>
</div>



  
</div>


{% endfor %} {% endblock %}

main_app/templates/home.html
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
{% extends 'base.html' %}

<!-- <!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" href="https://cdn-icons-png.flaticon.com/512/815/815832.png">
  <title></title>
</head>
<body> -->

    {% block content %}
    <div class="center">
  <h1>Crystal Collector</h1>
  <img src="https://totemsurftribe.files.wordpress.com/2024/04/3290fc01-e883-45d2-915a-7610ed0dc7f1.jpeg?resize=438%2C438" class="home-img">
</div>

  {% endblock %}
</body>
</html>

main_app/templates/main_app/collection_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete From Collection</h1>

  <h4>Are you sure you want to delete from<span class="black-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'collections_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/collection_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>{{ collection.name }} Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ collection.name }}</span>
        <p><img src="{{ collection.image }}" class="collection-img"></p>
      </div>
      <div class="card-action">
        <a href="{% url 'collections_update' collection.id %}">Edit</a>
        <a href="{% url 'collections_delete' collection.id %}">Delete</a>
        <a href="">View Collection</a>

      </div>
    </div>
  </div>
</div>



<!-- 


<hr>
<div class="row">
  <div class="col s6">
    <h5>{{ collection.name }} has the following Crystals</h5>
    {% if collection.crystals.count %}
    {% for collection in collection.crystals.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title">
          <span>{{ crystal.name }}</span> <img src="{{ crystal.image }}" class="detail-img">
        </span>
      </div>
      <div class="card-action">
        <form action="{% url 'remove_assoc_crystal' collection.id crystal.id %}" method="POST">
          {% csrf_token %}
          <button type="submit" class="btn">Remove</button>

        </form>
      </div>
    </div>
    {% endfor %}
    {% else %}
    <h5>No Crystals in this Collection Yet</h5>
    {% endif %}
  </div>


  <div class="col s6">
    <h4>Crystals in this Collection</h4>
    {% if crystals.count %}
    {% for crystal in crystals.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title">
          A <span>{{ crystal.name }}</span> <img src="{{ crystal.image }}" class="detail-img">
        </span>
      </div>
      <div class="card-action">
        <form action="{% url 'assoc_crystal' collection.id crystal.id %}" method="POST">
          {% csrf_token %}
          <button type="submit" class="btn">Add</button>
        </form>
      </div>
    </div>
    {% endfor %}
    {% else %}
    <h5>{{collection.name}} has all Crystals</h5>
    {% endif %}




  </div>
</div> -->
{% endblock %}

main_app/templates/main_app/collection_form.html
{% extends 'base.html' %} {% block content %} {% if object %}
<h1>Edit <span class="black-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Collection</h1>
{% endif %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="post">
  <!-- Django requires the following for security purposes -->
  {% csrf_token %}
  <table>
    <!-- Render the inputs inside of <tr>s & <td>s -->
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn" />
</form>
{% endblock %}

main_app/templates/main_app/collection_list.html
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
{% extends 'base.html' %}
{% block content %}

<h1>All Collections</h1>

{% for collection in collection_list %}

<a href="{% url 'collections_detail' collection.id %}">
  <div class="card">
    <div class="card-content">
      <span class="card-title" style="color:black">{{ collection.name }}</span>
      <p><img src="{{collection.image}}" class="collection-img"></p>
    </div>
  </div>
</a>

{% endfor %}



{% endblock %}

main_app/templates/main_app/crystal_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>Delete Crystal</h1>

<h4>Are you sure you want to delete <span class="teal-text">{{ crystal.name }}</span>?</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn">
  <a href="{% url 'detail' crystal.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/crystal_form.html
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
{% extends 'base.html' %}

{% block content%}
{% if object %}
    <h1>Edit <span class="purple-text">{{crystal.name}}</span></h1>
  {% else %}
  <h1>Add Crystal</h1>
  {% endif %}



<form action="{{ success_url }}" method="POST">

    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
</form>





{% endblock %}